<#
.SYNOPSIS
    Apply patches to managed_components/ and ESP-IDF that fix known issues.

.DESCRIPTION
    managed_components/ is regenerated by IDF Component Manager on every clean
    build, so these fixes cannot be committed to git.  Run this script once
    after a fresh clone (or after wiping managed_components/) to restore the
    working state.

    Patches applied:
      0001  esp_sdk_mem_lib.c  - rename enum member thread_local to
                                 thread_local_seg (C23 made it a keyword)
      0002  user_settings.h    - disable wolfssl HW acceleration for ESP32-S3
                                 (PERIPH_AES_MODULE / PERIPH_RSA_MODULE removed
                                 from ESP-IDF v6.0 periph_defs.h)
      0003  user_settings.h    - add WOLFSSL_ED25519_STREAMING_VERIFY
      0004  user_settings.h    - disable wolfssl HW acceleration for classic ESP32
                                 (same IDF v6.0 PERIPH_RSA_MODULE / clk_gate_ll breakage)
      0005  spi_bus_lock.c     - fix TOCTOU null-deref in bg_exit_core (ESP-IDF v6.0 bug)
                                 acquiring_dev is volatile and can be cleared between the
                                 null-check and the DEV_BG_MASK() dereference; snapshot
                                 it into a local variable to close the race window.
                                 Crash symptom: LoadProhibited at EXCVADDR=0x8 inside
                                 ppTask -> bg_exit_core (spi_bus_lock.c:549) during
                                 BT A2DP + WiFi operation.
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot

function Patch-File {
    param(
        [string]$RelPath,
        [string]$OldText,
        [string]$NewText,
        [string]$Description
    )

    $FullPath = Join-Path $Root $RelPath

    if (-not (Test-Path $FullPath)) {
        Write-Warning "SKIP  $RelPath  (file not found - run idf.py build once first to populate managed_components/)"
        return
    }

    $content = Get-Content $FullPath -Raw -Encoding UTF8

    if ($content.Contains($NewText)) {
        Write-Host "SKIP  $Description  (already applied)" -ForegroundColor DarkGray
        return
    }

    if (-not $content.Contains($OldText)) {
        Write-Warning "SKIP  $Description  (original text not found - wolfssl version may differ)"
        return
    }

    $patched = $content.Replace($OldText, $NewText)
    [System.IO.File]::WriteAllText($FullPath, $patched, [System.Text.UTF8Encoding]::new($false))
    Write-Host "OK    $Description" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Patch 0001 - esp_sdk_mem_lib.c: thread_local -> thread_local_seg
# ---------------------------------------------------------------------------
Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    thread_local, /* thread_local_start to thread_local_end */" `
    -NewText      "    thread_local_seg, /* renamed from thread_local: C23 made thread_local a keyword */" `
    -Description  "0001 esp_sdk_mem_lib.c enum member thread_local -> thread_local_seg"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    sdk_log_meminfo(thread_local,  _thread_local_start, _thread_local_end);" `
    -NewText      "    sdk_log_meminfo(thread_local_seg,  _thread_local_start, _thread_local_end);" `
    -Description  "0001 esp_sdk_mem_lib.c usage thread_local -> thread_local_seg"

# ---------------------------------------------------------------------------
# Patch 0002 - user_settings.h: disable wolfssl HW crypto for ESP32-S3
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* wolfSSL HW Acceleration supported on ESP32-S3. Uncomment to disable: */`n    /*  #define NO_ESP32_CRYPT                 */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_HASH    */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_AES     */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD */`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"
$new02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* Hardware acceleration disabled for ESP-IDF v6.0 compatibility.`n     * PERIPH_AES_MODULE / PERIPH_RSA_MODULE were removed from periph_defs.h`n     * in IDF v6.0, and clk_gate_ll.h moved to esp_hal_clock component.`n     * Fall back to software crypto.`n     * Note: Must define all NO_WOLFSSL_ESP32_CRYPT_* here (not just`n     * NO_ESP32_CRYPT) because sha.h checks NO_WOLFSSL_ESP32_CRYPT_HASH`n     * before esp32-crypt.h is included. */`n    #define NO_ESP32_CRYPT`n    #define NO_WOLFSSL_ESP32_CRYPT_HASH`n    #define NO_WOLFSSL_ESP32_CRYPT_AES`n    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old02 `
    -NewText      $new02 `
    -Description  "0002 user_settings.h disable HW crypto for ESP32-S3 / IDF v6.0"

# ---------------------------------------------------------------------------
# Patch 0003 - user_settings.h: add WOLFSSL_ED25519_STREAMING_VERIFY
# wolfSSH >= 1.4.20 internal.h forces WOLFSSH_NO_ED25519 (disabling ed25519
# user auth entirely) unless WOLFSSL_ED25519_STREAMING_VERIFY is defined.
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old03 = "    /* ED25519 requires SHA512 */`n    #define HAVE_ED25519`n#endif"
$new03 = "    /* ED25519 requires SHA512 */`n    #define HAVE_ED25519`n    /* wolfSSH >= 1.4.20 requires WOLFSSL_ED25519_STREAMING_VERIFY.`n     * Without it, wolfssh/internal.h forces WOLFSSH_NO_ED25519, completely`n     * disabling ed25519 user auth (ssh-ed25519 public key login). */`n    #define WOLFSSL_ED25519_STREAMING_VERIFY`n#endif"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old03 `
    -NewText      $new03 `
    -Description  "0003 user_settings.h add WOLFSSL_ED25519_STREAMING_VERIFY for wolfssh 1.4.20"

# ---------------------------------------------------------------------------
# Patch 0004 - user_settings.h: disable wolfssl HW crypto for classic ESP32
# Same root cause as patch 0002: PERIPH_RSA_MODULE was removed in IDF v6.0
# and hal/clk_gate_ll.h moved to esp_hal_clock which wolfssl doesn't declare.
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old04 = "#if defined(CONFIG_IDF_TARGET_ESP32) || defined(WOLFSSL_ESPWROOM32SE)`n    #define WOLFSSL_ESP32`n    /*  Alternatively, if there's an ECC Secure Element present: */`n    /* #define WOLFSSL_ESPWROOM32SE */`n`n    /* wolfSSL HW Acceleration supported on ESP32. Uncomment to disable: */`n    /*  #define NO_ESP32_CRYPT                 */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_HASH    */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_AES     */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD */"
$new04 = "#if defined(CONFIG_IDF_TARGET_ESP32) || defined(WOLFSSL_ESPWROOM32SE)`n    #define WOLFSSL_ESP32`n    /*  Alternatively, if there's an ECC Secure Element present: */`n    /* #define WOLFSSL_ESPWROOM32SE */`n`n    /* Hardware acceleration disabled for ESP-IDF v6.0 compatibility.`n     * PERIPH_RSA_MODULE was removed from periph_defs.h in IDF v6.0, and`n     * hal/clk_gate_ll.h moved to the esp_hal_clock component which wolfssl`n     * does not declare as a dependency.  Fall back to software crypto. */`n    #define NO_ESP32_CRYPT`n    #define NO_WOLFSSL_ESP32_CRYPT_HASH`n    #define NO_WOLFSSL_ESP32_CRYPT_AES`n    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old04 `
    -NewText      $new04 `
    -Description  "0004 user_settings.h disable HW crypto for classic ESP32 / IDF v6.0"

# ---------------------------------------------------------------------------
# Patch 0005 - spi_bus_lock.c: fix TOCTOU null-deref in bg_exit_core
# ESP-IDF v6.0 bug: lock->acquiring_dev is volatile and can be set to NULL by
# another task between the null-check (line 548) and DEV_BG_MASK() dereference
# (line 549), causing LoadProhibited at EXCVADDR=0x8 (NULL+8).
# Fix: snapshot the pointer once into a local variable before the check.
# ---------------------------------------------------------------------------
$idfSpiLock = "C:\esp\v6.0\esp-idf\components\esp_hw_support\spi_bus_lock.c"
if (-not (Test-Path $idfSpiLock)) {
    Write-Warning "SKIP  0005 spi_bus_lock.c TOCTOU fix  (ESP-IDF not found at C:\esp\v6.0)"
} else {
    # Use single-quoted here-strings so backtick characters in C comments are
    # treated literally (double-quoted @"..."@ would consume them as PS escapes).
    $old05 = @'
    bool ret;
    uint32_t status = lock_status_fetch(lock);
    if (lock->acquiring_dev) {
        if (status & DEV_BG_MASK(lock->acquiring_dev)) {
            BUS_LOCK_DEBUG_EXECUTE_CHECK(lock->acq_dev_bg_active);
            ret = false;
        } else {
            // The request may happen any time, even after we fetched the status.
            // The value of `acq_dev_bg_active` is random.
            resume_dev_in_isr(lock->acquiring_dev, do_yield);
            ret = true;
        }
    } else {
'@
    $new05 = @'
    bool ret;
    uint32_t status = lock_status_fetch(lock);
    /* Snapshot acquiring_dev once: it is a volatile pointer and can be set to
     * NULL by another task between the null-check and the dereference, causing
     * a LoadProhibited crash (EXCVADDR=0x8) in DEV_BG_MASK(). */
    spi_bus_lock_dev_t *acq_dev = lock->acquiring_dev;
    if (acq_dev) {
        if (status & DEV_BG_MASK(acq_dev)) {
            BUS_LOCK_DEBUG_EXECUTE_CHECK(lock->acq_dev_bg_active);
            ret = false;
        } else {
            // The request may happen any time, even after we fetched the status.
            // The value of `acq_dev_bg_active` is random.
            resume_dev_in_isr(acq_dev, do_yield);
            ret = true;
        }
    } else {
'@
    # Normalise CRLF->LF in case the PS script has CRLF line endings
    $old05n = $old05 -replace "`r`n", "`n"
    $new05n = $new05 -replace "`r`n", "`n"
    $content = Get-Content $idfSpiLock -Raw -Encoding UTF8
    if ($content.Contains($new05n)) {
        Write-Host "SKIP  0005 spi_bus_lock.c TOCTOU fix  (already applied)" -ForegroundColor DarkGray
    } elseif (-not $content.Contains($old05n)) {
        Write-Warning "SKIP  0005 spi_bus_lock.c TOCTOU fix  (original text not found - ESP-IDF version may differ)"
    } else {
        $patched = $content.Replace($old05n, $new05n)
        [System.IO.File]::WriteAllText($idfSpiLock, $patched, [System.Text.UTF8Encoding]::new($false))
        Write-Host "OK    0005 spi_bus_lock.c TOCTOU fix" -ForegroundColor Green
    }
}

# ---------------------------------------------------------------------------
# Patch 0006 - l2c_link.c: demote is_cong_cback_context log from ERROR to DEBUG
# ESP-IDF v6.0 Bluedroid fires L2CAP_TRACE_ERROR("l2cab is_cong_cback_context")
# at 100+ times/second during normal A2DP + WiFi coexistence RF congestion.
# Each call string-formats and serializes to UART, stealing CPU from BT audio
# tasks and directly causing audio glitches.  The guard itself (return;) is
# correct and should stay.  Only the log level needs demotion so it is silent
# in production while remaining visible when BT debug tracing is enabled.
# ---------------------------------------------------------------------------
$l2cLink = "C:\esp\v6.0\esp-idf\components\bt\host\bluedroid\stack\l2cap\l2c_link.c"
if (-not (Test-Path $l2cLink)) {
    Write-Warning "SKIP  0006 l2c_link.c is_cong_cback_context ERROR->DEBUG  (ESP-IDF not found at C:\esp\v6.0)"
} else {
    $old06 = '        L2CAP_TRACE_ERROR("l2cab is_cong_cback_context");'
    $new06 = '        L2CAP_TRACE_DEBUG("l2cab is_cong_cback_context");'
    $content06 = Get-Content $l2cLink -Raw -Encoding UTF8
    if ($content06.Contains($new06)) {
        Write-Host "SKIP  0006 l2c_link.c is_cong_cback_context ERROR->DEBUG  (already applied)" -ForegroundColor DarkGray
    } elseif (-not $content06.Contains($old06)) {
        Write-Warning "SKIP  0006 l2c_link.c is_cong_cback_context ERROR->DEBUG  (original text not found - ESP-IDF version may differ)"
    } else {
        $patched06 = $content06.Replace($old06, $new06)
        [System.IO.File]::WriteAllText($l2cLink, $patched06, [System.Text.UTF8Encoding]::new($false))
        Write-Host "OK    0006 l2c_link.c is_cong_cback_context ERROR->DEBUG" -ForegroundColor Green
    }
}

Write-Host "`nDone." -ForegroundColor Cyan