<#
.SYNOPSIS
    Apply patches to managed_components/ that fix wolfssl 5.8.2 incompatibilities
    with ESP-IDF v6.0 (C23 + removed periph module defines).

.DESCRIPTION
    managed_components/ is regenerated by IDF Component Manager on every clean
    build, so these fixes cannot be committed to git.  Run this script once
    after a fresh clone (or after wiping managed_components/) to restore the
    working state.

    Patches applied:
      0001  esp_sdk_mem_lib.c  - rename enum member thread_local to
                                 thread_local_seg (C23 made it a keyword)
      0002  user_settings.h    - disable wolfssl HW acceleration for ESP32-S3
                                 (PERIPH_AES_MODULE / PERIPH_RSA_MODULE removed
                                 from ESP-IDF v6.0 periph_defs.h)
      0003  user_settings.h    - add WOLFSSL_ED25519_STREAMING_VERIFY
      0004  user_settings.h    - disable wolfssl HW acceleration for classic ESP32
                                 (same IDF v6.0 PERIPH_RSA_MODULE / clk_gate_ll breakage)
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot

function Patch-File {
    param(
        [string]$RelPath,
        [string]$OldText,
        [string]$NewText,
        [string]$Description
    )

    $FullPath = Join-Path $Root $RelPath

    if (-not (Test-Path $FullPath)) {
        Write-Warning "SKIP  $RelPath  (file not found - run idf.py build once first to populate managed_components/)"
        return
    }

    $content = Get-Content $FullPath -Raw -Encoding UTF8

    if ($content.Contains($NewText)) {
        Write-Host "SKIP  $Description  (already applied)" -ForegroundColor DarkGray
        return
    }

    if (-not $content.Contains($OldText)) {
        Write-Warning "SKIP  $Description  (original text not found - wolfssl version may differ)"
        return
    }

    $patched = $content.Replace($OldText, $NewText)
    [System.IO.File]::WriteAllText($FullPath, $patched, [System.Text.UTF8Encoding]::new($false))
    Write-Host "OK    $Description" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Patch 0001 - esp_sdk_mem_lib.c: thread_local -> thread_local_seg
# ---------------------------------------------------------------------------
Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    thread_local, /* thread_local_start to thread_local_end */" `
    -NewText      "    thread_local_seg, /* renamed from thread_local: C23 made thread_local a keyword */" `
    -Description  "0001 esp_sdk_mem_lib.c enum member thread_local -> thread_local_seg"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    sdk_log_meminfo(thread_local,  _thread_local_start, _thread_local_end);" `
    -NewText      "    sdk_log_meminfo(thread_local_seg,  _thread_local_start, _thread_local_end);" `
    -Description  "0001 esp_sdk_mem_lib.c usage thread_local -> thread_local_seg"

# ---------------------------------------------------------------------------
# Patch 0002 - user_settings.h: disable wolfssl HW crypto for ESP32-S3
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* wolfSSL HW Acceleration supported on ESP32-S3. Uncomment to disable: */`n    /*  #define NO_ESP32_CRYPT                 */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_HASH    */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_AES     */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD */`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"
$new02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* Hardware acceleration disabled for ESP-IDF v6.0 compatibility.`n     * PERIPH_AES_MODULE / PERIPH_RSA_MODULE were removed from periph_defs.h`n     * in IDF v6.0, and clk_gate_ll.h moved to esp_hal_clock component.`n     * Fall back to software crypto.`n     * Note: Must define all NO_WOLFSSL_ESP32_CRYPT_* here (not just`n     * NO_ESP32_CRYPT) because sha.h checks NO_WOLFSSL_ESP32_CRYPT_HASH`n     * before esp32-crypt.h is included. */`n    #define NO_ESP32_CRYPT`n    #define NO_WOLFSSL_ESP32_CRYPT_HASH`n    #define NO_WOLFSSL_ESP32_CRYPT_AES`n    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old02 `
    -NewText      $new02 `
    -Description  "0002 user_settings.h disable HW crypto for ESP32-S3 / IDF v6.0"

# ---------------------------------------------------------------------------
# Patch 0003 - user_settings.h: add WOLFSSL_ED25519_STREAMING_VERIFY
# wolfSSH >= 1.4.20 internal.h forces WOLFSSH_NO_ED25519 (disabling ed25519
# user auth entirely) unless WOLFSSL_ED25519_STREAMING_VERIFY is defined.
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old03 = "    /* ED25519 requires SHA512 */`n    #define HAVE_ED25519`n#endif"
$new03 = "    /* ED25519 requires SHA512 */`n    #define HAVE_ED25519`n    /* wolfSSH >= 1.4.20 requires WOLFSSL_ED25519_STREAMING_VERIFY.`n     * Without it, wolfssh/internal.h forces WOLFSSH_NO_ED25519, completely`n     * disabling ed25519 user auth (ssh-ed25519 public key login). */`n    #define WOLFSSL_ED25519_STREAMING_VERIFY`n#endif"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old03 `
    -NewText      $new03 `
    -Description  "0003 user_settings.h add WOLFSSL_ED25519_STREAMING_VERIFY for wolfssh 1.4.20"

# ---------------------------------------------------------------------------
# Patch 0004 - user_settings.h: disable wolfssl HW crypto for classic ESP32
# Same root cause as patch 0002: PERIPH_RSA_MODULE was removed in IDF v6.0
# and hal/clk_gate_ll.h moved to esp_hal_clock which wolfssl doesn't declare.
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old04 = "#if defined(CONFIG_IDF_TARGET_ESP32) || defined(WOLFSSL_ESPWROOM32SE)`n    #define WOLFSSL_ESP32`n    /*  Alternatively, if there's an ECC Secure Element present: */`n    /* #define WOLFSSL_ESPWROOM32SE */`n`n    /* wolfSSL HW Acceleration supported on ESP32. Uncomment to disable: */`n    /*  #define NO_ESP32_CRYPT                 */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_HASH    */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_AES     */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD */"
$new04 = "#if defined(CONFIG_IDF_TARGET_ESP32) || defined(WOLFSSL_ESPWROOM32SE)`n    #define WOLFSSL_ESP32`n    /*  Alternatively, if there's an ECC Secure Element present: */`n    /* #define WOLFSSL_ESPWROOM32SE */`n`n    /* Hardware acceleration disabled for ESP-IDF v6.0 compatibility.`n     * PERIPH_RSA_MODULE was removed from periph_defs.h in IDF v6.0, and`n     * hal/clk_gate_ll.h moved to the esp_hal_clock component which wolfssl`n     * does not declare as a dependency.  Fall back to software crypto. */`n    #define NO_ESP32_CRYPT`n    #define NO_WOLFSSL_ESP32_CRYPT_HASH`n    #define NO_WOLFSSL_ESP32_CRYPT_AES`n    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old04 `
    -NewText      $new04 `
    -Description  "0004 user_settings.h disable HW crypto for classic ESP32 / IDF v6.0"

Write-Host "`nDone." -ForegroundColor Cyan