<#
.SYNOPSIS
    Apply patches to managed_components/ that fix wolfssl 5.8.2 incompatibilities
    with ESP-IDF v6.0 (C23 + removed periph module defines).

.DESCRIPTION
    managed_components/ is regenerated by IDF Component Manager on every clean
    build, so these fixes cannot be committed to git.  Run this script once
    after a fresh clone (or after wiping managed_components/) to restore the
    working state.

    Patches applied:
      0001  esp_sdk_mem_lib.c  - rename enum member thread_local to
                                 thread_local_seg (C23 made it a keyword)
      0002  user_settings.h    - disable wolfssl HW acceleration for ESP32-S3
                                 (PERIPH_AES_MODULE / PERIPH_RSA_MODULE removed
                                 from ESP-IDF v6.0 periph_defs.h)
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot

function Patch-File {
    param(
        [string]$RelPath,
        [string]$OldText,
        [string]$NewText,
        [string]$Description
    )

    $FullPath = Join-Path $Root $RelPath

    if (-not (Test-Path $FullPath)) {
        Write-Warning "SKIP  $RelPath  (file not found - run idf.py build once first to populate managed_components/)"
        return
    }

    $content = Get-Content $FullPath -Raw -Encoding UTF8

    if ($content.Contains($NewText)) {
        Write-Host "SKIP  $Description  (already applied)" -ForegroundColor DarkGray
        return
    }

    if (-not $content.Contains($OldText)) {
        Write-Warning "SKIP  $Description  (original text not found - wolfssl version may differ)"
        return
    }

    $patched = $content.Replace($OldText, $NewText)
    [System.IO.File]::WriteAllText($FullPath, $patched, [System.Text.UTF8Encoding]::new($false))
    Write-Host "OK    $Description" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Patch 0001 - esp_sdk_mem_lib.c: thread_local -> thread_local_seg
# ---------------------------------------------------------------------------
Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    thread_local, /* thread_local_start to thread_local_end */" `
    -NewText      "    thread_local_seg, /* renamed from thread_local: C23 made thread_local a keyword */" `
    -Description  "0001 esp_sdk_mem_lib.c enum member thread_local -> thread_local_seg"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\wolfcrypt\src\port\Espressif\esp_sdk_mem_lib.c" `
    -OldText      "    sdk_log_meminfo(thread_local,  _thread_local_start, _thread_local_end);" `
    -NewText      "    sdk_log_meminfo(thread_local_seg,  _thread_local_start, _thread_local_end);" `
    -Description  "0001 esp_sdk_mem_lib.c usage thread_local -> thread_local_seg"

# ---------------------------------------------------------------------------
# Patch 0002 - user_settings.h: disable wolfssl HW crypto for ESP32-S3
# user_settings.h uses LF-only line endings (downloaded from component registry)
# ---------------------------------------------------------------------------
$old02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* wolfSSL HW Acceleration supported on ESP32-S3. Uncomment to disable: */`n    /*  #define NO_ESP32_CRYPT                 */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_HASH    */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_AES     */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD  */`n    /*  #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD */`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"
$new02 = "#elif defined(CONFIG_IDF_TARGET_ESP32S3)`n    #define WOLFSSL_ESP32`n    /* Hardware acceleration disabled for ESP-IDF v6.0 compatibility.`n     * PERIPH_AES_MODULE / PERIPH_RSA_MODULE were removed from periph_defs.h`n     * in IDF v6.0, and clk_gate_ll.h moved to esp_hal_clock component.`n     * Fall back to software crypto.`n     * Note: Must define all NO_WOLFSSL_ESP32_CRYPT_* here (not just`n     * NO_ESP32_CRYPT) because sha.h checks NO_WOLFSSL_ESP32_CRYPT_HASH`n     * before esp32-crypt.h is included. */`n    #define NO_ESP32_CRYPT`n    #define NO_WOLFSSL_ESP32_CRYPT_HASH`n    #define NO_WOLFSSL_ESP32_CRYPT_AES`n    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI`n    /***** END CONFIG_IDF_TARGET_ESP32S3 *****/"

Patch-File `
    -RelPath      "managed_components\wolfssl__wolfssl\include\user_settings.h" `
    -OldText      $old02 `
    -NewText      $new02 `
    -Description  "0002 user_settings.h disable HW crypto for ESP32-S3 / IDF v6.0"

Write-Host "`nDone." -ForegroundColor Cyan